name: 🦺 Validate build status

on:
  push:
    branches: [ "alpha" ]
    
  pull_request:
    branches: [ "alpha", "beta", "main" ]

jobs:
  build:
    name: 🔨 Build Carbon on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    
    steps:
    - name: 🔗 Checkout source code from github
      uses: actions/checkout@v3

    - name: 🛤️ Setup the build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: 🐧 Execute the build process on Linux
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/dev_init.sh
        ${GITHUB_WORKSPACE}/Tools/Build/linux/dev_release.sh

    - name: 🪟 Execute the build process on Windows
      shell: cmd
      if: matrix.os == 'windows-latest'
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\dev_init.bat
        %GITHUB_WORKSPACE%\Tools\Build\win\dev_release.bat

    - name: ⬆️ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-build-${{ matrix.os }}-${{ github.run_id }}
        path: Release
