# 
#   ______ _______ ______ ______ _______ _______ 
#  |      |   _   |   __ \   __ \       |    |  |
#  |   ---|       |      <   __ <   -   |       |
#  |______|___|___|___|__|______/_______|__|____|
#                         discord.gg/eXPcNKK4yd
# 
name: 🪣 Invalidate cache(s)

on:
  # allow manual action trigger
  workflow_dispatch:
  
  #schedule:
    #- cron: '0 7 * * *'
    # technically this is more a "morningly" build
    # but we do work late.. :-)

jobs:
  managed-data:
    name: 🦺 Clear rust managed data and tools 
    runs-on: ubuntu-latest
      
    steps:
    - name: 📦 Cache rust managed data and tools
      uses: actions/cache@v3
      with:
        path: |
          Rust/RustDedicated_Data
          Tools/NStrip/NStrip/bin
          Tools/DepotDownloader/DepotDownloader/bin
        key: cache-rust-managed

    - if: steps.cache-rust-managed.outputs.cache-hit == 'true'
      name: 🧹 Clear cached rust managed data and tools
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.actions.deleteActionsCacheByKey({
            owner: context.repo.owner,
            repo: context.repo.repo,
            key: "cache-rust-managed"
          })
